# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
#baseurl                 = "https://example.com/"
DefaultContentLanguage  = "en"
title                   = "Ghotfall's Corner"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = [""]
enableEmoji				= true

[outputs]
  home                  = ["html", "json"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]

  [params.meta]
    description         = "Ghotfall's personal blog"
    author              = "Andrii Myrhorodskyi"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Ghotfall's Corner"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = false
    languageMenu        = false

  [params.intro]
    header                = "Ghotfall's Corner"
    paragraph             = "Here you can find a lot of interesting stories about life, work, hobbies and even more!"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = true
    alwaysOnHomepage      = true

    [params.intro.pic]
      src                 = "/img/main/logo.jpg"
      shape               = "message"
      width               = "200px"
      alt                 = "Ghotfall's corner"

  [params.sidebar]
    about               = "Learn more about Andrii \"Ghotfall\" Myrhorodskyi"
    postAmount          = 3
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = false
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='fa fa-user'></i>"
    weight            = 4

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='fa fa-th'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fa fa-bars'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "/contact/"
    pre               = "<i class='fa fa-paper-plane'></i>"
    weight            = 5

[social]
  # Coding Communities
  github                = "ghotfall"
  gitlab                = "ghotfall"
  stackoverflow         = "" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""
  # Visual Art Communities
  deviantart            = ""
  flickr                = ""
  behance               = ""
  dribbble              = ""
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = ""
  linkedin_company      = ""
  foursquare            = ""
  xing                  = ""
  slideshare            = ""
  # Social Networks
  facebook              = "100004706048519"
  googleplus            = ""
  reddit                = "ghotfall"
  quora                 = ""
  youtube               = ""
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = "ghotfall"
  tumblr                = ""
  twitter               = ""
  strava                = ""
  skype                 = ""
  snapchat              = ""
  pinterest             = "ghotfall"
  telegram              = "ghotfall"
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  researchgate          = ""
  keybase               = ""
  mastodon              = ""
  # Email
  email                 = ""
